apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sleep", "10"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Never