apiVersion: v1
kind: Service
metadata:
  name: postgres-exp-svc
  labels:
    app: postgres16-exp
spec:
  type: NodePort
  selector:
    app: postgres16-exp
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-exp-pvc
  labels:
    app: postgres16-exp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: "openebs-hostpath"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres16-exp
  labels:
    app: postgres16-exp
spec:
  selector:
    matchLabels:
      app: postgres16-exp
  template:
    metadata:
      labels:
        app: postgres16-exp
    spec:
      containers:
      - image: junhp1234/postgresql-16.3-alpine-huge-pages:latest
        name: postgres16-exp
        env:
        - name: POSTGRES_PASSWORD
          value: gcexp          
        - name: POSTGRES_DB
          value: gcexp
        - name: POSTGRES_USER
          value: gcexp
        args:
          - "-c"
          - "shared_buffers=4096MB"
          - "-c"
          - "max_connections=1000"
        ports:
        - containerPort: 5432
          name: postgres16-exp
        volumeMounts:
        - name: postgres-exp-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-exp-storage
        persistentVolumeClaim:
          claimName: postgres-exp-pvc
